################################################################################
#
# Makefile to build the network server demo program
#
################################################################################

TARGETS = server client

CC = gcc
CCFLAGS = 

all: $(TARGETS)

clean:
	rm -f $(TARGETS)

%: %.c
	$(CC) $(CCFLAGS) -o $@ $^


















